# Generated by Django 5.0.2 on 2024-02-28 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ManagerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_description', models.CharField(max_length=2000)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.packages')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.user')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_date', models.DateField(auto_created=True)),
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.packages')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.user')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
