# Generated by Django 5.0.2 on 2024-03-31 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0001_initial'),
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiery',
            fields=[
                ('enquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(max_length=10)),
                ('enquiry_description', models.CharField(max_length=2000)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.packages')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.user')),
            ],
            options={
                'db_table': 'enquiries',
            },
        ),
    ]
