# Generated by Django 5.0.2 on 2024-04-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_enquieries_delete_enquiery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquire',
            fields=[
                ('enquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'enquire',
            },
        ),
        migrations.DeleteModel(
            name='Enquieries',
        ),
    ]
