# Generated by Django 5.0.2 on 2024-04-04 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_enquire_delete_enquieries'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enquire',
            new_name='UserEnquieries',
        ),
        migrations.AlterModelTable(
            name='userenquieries',
            table='enquiries',
        ),
    ]
