# Generated by Django 5.0.2 on 2024-05-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('manager_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'manager',
            },
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=150)),
                ('short_description', models.CharField(max_length=500)),
                ('full_description', models.CharField(max_length=2000)),
                ('area_covers', models.CharField(max_length=1000)),
                ('package_image', models.ImageField(null=True, upload_to='images')),
            ],
            options={
                'db_table': 'packages',
            },
        ),
    ]
